use nhn_academy_32;

-- MySQL Script generated by MySQL Workbench
-- Sun May 24 18:12:08 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projects` (
                                          `id` BIGINT NOT NULL AUTO_INCREMENT,
                                          `name` VARCHAR(45) NOT NULL,
    `state` ENUM('ACTIVE', 'DORMANT', 'CLOSED') NOT NULL,
    `created_at` DATETIME NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
                                       `id` BIGINT NOT NULL AUTO_INCREMENT,
                                       `email` VARCHAR(200) NOT NULL,
    `user_id` VARCHAR(200) NOT NULL,
    `password` VARCHAR(200) NOT NULL,
    `created_at` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `milestones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milestones` (
                                            `id` BIGINT NOT NULL AUTO_INCREMENT,
                                            `name` VARCHAR(50) NOT NULL,
    `project_id` BIGINT NOT NULL,
    `start_date` DATETIME NULL DEFAULT NULL,
    `end_date` DATETIME NULL DEFAULT NULL,
    `created_at` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_milestones_projects1_idx` (`project_id` ASC) VISIBLE,
    CONSTRAINT `fk_milestones_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_members` (
                                                 `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                 `project_id` BIGINT NOT NULL,
                                                 `user_id` BIGINT NOT NULL,
                                                 `role` ENUM('ADMIN', 'MEMBER') NOT NULL,
    `is_deleted` TINYINT NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    INDEX `fk_projects_has_users_projects_idx` (`project_id` ASC) VISIBLE,
    CONSTRAINT `fk_projects_has_users_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tasks` (
                                       `id` BIGINT NOT NULL AUTO_INCREMENT,
                                       `project_id` BIGINT NOT NULL,
                                       `project_members_id` BIGINT NOT NULL,
                                       `milestone_id` BIGINT NULL DEFAULT NULL,
                                       `name` VARCHAR(200) NOT NULL,
    `content` VARCHAR(200) NOT NULL,
    `created_at` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tasks_projects1_idx` (`project_id` ASC) VISIBLE,
    INDEX `fk_tasks_milestones1_idx` (`milestone_id` ASC) VISIBLE,
    INDEX `fk_tasks_project_members1_idx` (`project_members_id` ASC) VISIBLE,
    CONSTRAINT `fk_tasks_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_tasks_milestones1`
    FOREIGN KEY (`milestone_id`)
    REFERENCES `milestones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_tasks_project_members1`
    FOREIGN KEY (`project_members_id`)
    REFERENCES `project_members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tags` (
                                      `id` BIGINT NOT NULL AUTO_INCREMENT,
                                      `project_id` BIGINT NOT NULL,
                                      `name` VARCHAR(50) NOT NULL,
    `created_at` DATETIME NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_tags_projects1_idx` (`project_id` ASC) VISIBLE,
    UNIQUE INDEX `uk_project_id_name` (`project_id` ASC, `name` ASC) VISIBLE,
    CONSTRAINT `fk_tags_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `projects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `comments` (
                                          `id` BIGINT NOT NULL AUTO_INCREMENT,
                                          `task_id` BIGINT NOT NULL,
                                          `project_member_id` BIGINT NOT NULL,
                                          `content` VARCHAR(45) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_comments_tasks1_idx` (`task_id` ASC) VISIBLE,
    INDEX `fk_comments_project_members1_idx` (`project_member_id` ASC) VISIBLE,
    CONSTRAINT `fk_comments_tasks1`
    FOREIGN KEY (`task_id`)
    REFERENCES `tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_comments_project_members1`
    FOREIGN KEY (`project_member_id`)
    REFERENCES `project_members` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `task_tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `task_tag` (
                                          `id` BIGINT NOT NULL AUTO_INCREMENT,
                                          `tag_id` BIGINT NOT NULL,
                                          `task_id` BIGINT NOT NULL,
                                          PRIMARY KEY (`id`),
    INDEX `fk_tags_has_tasks_tasks1_idx` (`task_id` ASC) VISIBLE,
    INDEX `fk_tags_has_tasks_tags1` (`tag_id` ASC) VISIBLE,
    CONSTRAINT `fk_tags_has_tasks_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_tags_has_tasks_tasks1`
    FOREIGN KEY (`task_id`)
    REFERENCES `tasks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
